version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qa1k-onyx_web_1
      APP_PORT: 80

  web:
    image: nginx:1.27-alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
